### ISSUE TITLE
Login UI fails to get enduser info

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#658] opened 2022-11-03 17:53 UTC
When the PSU (bank account owner) logs in, the UI then tries to make the following request (this is the curl equivalent):

```
curl 'https://iam.bohocode.forgerock.financial/enduser?realm=/alpha&authIndexType=service&authIndexValue=PSD2SecureCustomerAuthentication' \
  -H 'authority: iam.bohocode.forgerock.financial' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'accept-language: en-GB,en;q=0.9' \
  -H 'cookie: amlbcookie=01; iPlanetDirectoryPro=Jf1GhjZaVRtKmBJ_8SsN1c6XsXQ.*AAJTSQACMDIAAlNLABxINVBmcW1EMVpjaUdkZERaOURRZ2IxZVdRVzg9AAR0eXBlAANDVFMAAlMxAAIwMQ..*' \
  -H 'referer: https://obdemo.bohocode.forgerock.financial/' \
  -H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  --compressed
  ```
  
This results in a 404 response.
The redirect url looks invalid, in a working environment there is no redirect to /enduser at any point.

**Comment by dbadham-fr** [comment] 2022-11-04 11:29
The issue is with authenticate success redirection url configuration.

As part of authentication, AM UI makes a call to the backend to validate the goto url to redirect to.

Example call the UI is making (extra headers removed)
```
curl 'https://iam.dbadham-fr.forgerock.financial/am/json/users?_action=validateGoto' \
 -X POST \
--data-raw '{"goto":"https://obdemo.dbadham-fr.forgerock.financial/am/oauth2/realms/root/realms/alpha/authorize?client_id=233c547d-77f7-4ce0-bfd8-976c59df5530&response_type=code%20id_token&redirect_uri=https://postman-echo.com/get&scope=openid%20payments&state=10d260bf-a7d9-444a-92d9-7b7a5f088208&nonce=10d260bf-a7d9-444a-92d9-7b7a5f088208&request=eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiJ9.eyJhdWQiOiJodHRwczovL29iZGVtby5kYmFkaGFtLWZyLmZvcmdlcm9jay5maW5hbmNpYWwvYW0vb2F1dGgyL3JlYWxtcy9yb290L3JlYWxtcy9hbHBoYSIsInNjb3BlIjoib3BlbmlkIGFjY291bnRzIiwiaXNzIjoiMjMzYzU0N2QtNzdmNy00Y2UwLWJmZDgtOTc2YzU5ZGY1NTMwIiwiY2xhaW1zIjp7ImlkX3Rva2VuIjp7ImFjciI6eyJ2YWx1ZSI6InVybjpvcGVuYmFua2luZzpwc2QyOmNhIiwiZXNzZW50aWFsIjp0cnVlfSwib3BlbmJhbmtpbmdfaW50ZW50X2lkIjp7InZhbHVlIjoiQUFDXzQyOGYyZDY2LTE1ODYtNGI5Zi1iMTFjLWJhYzNmNDVmOTQ2YSIsImVzc2VudGlhbCI6dHJ1ZX19fSwicmVzcG9uc2VfdHlwZSI6ImNvZGUgaWRfdG9rZW4iLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3Bvc3RtYW4tZWNoby5jb20vZ2V0Iiwic3RhdGUiOiIxMGQyNjBiZi1hN2Q5LTQ0NGEtOTJkOS03YjdhNWYwODgyMDgiLCJub25jZSI6IjEwZDI2MGJmLWE3ZDktNDQ0YS05MmQ5LTdiN2E1ZjA4ODIwOCIsImNsaWVudF9pZCI6IjIzM2M1NDdkLTc3ZjctNGNlMC1iZmQ4LTk3NmM1OWRmNTUzMCIsImlhdCI6MTY2NzU2MDYwNSwibmJmIjoxNjY3NTYwNjA1LCJleHAiOjE2Njc1NjEyMTAsImp0aSI6Ii1BNUVVblBhUVhhdTY2YkdkT2kzMyJ9.LL5l2KkbNnpmyo9NIhDr-ikLoZfwWyZMYeMrr4LP4O1IbbUUKAMYWdhYxVn0zpU7n5og6Q5t394TuY7hNS2fKb6ZVgrrztfzd4MA2Nu2EuXVGnWLhG6_DybSKKNsoLWzbqv7E_BPVqG95KdSjGPdiYWdCqoQzZmS8xQvIWjbh8GCiJlfG5sWU4IxTi55Vcjo-8hg2OXBR5g740rq7-76hqHN-eBQku7GhxPXb0DEEgvwlC-VQLWzufV6FWkEKkyM3ZMASgO1YvbkBeZoUxTZBD-jKdNJlIDevtamjihMqzmmORk4dzqDvDsbkWN8rAbCxYEp45LJNuHRPqOMswm1qw&acr=urn:openbanking:psd2:ca&acr_sig=Y-Ilpv79igcx0_DVkPYUpWPiXHBVYxUvQlPIjfsqcw4&acr=urn%3Aopenbanking%3Apsd2%3Aca&acr_sig=Y-Ilpv79igcx0_DVkPYUpWPiXHBVYxUvQlPIjfsqcw4"}'
```
If the goto url is valid, then we expect to see it returned as the successURL in the response, instead we were seeing the following response:
```
{"successURL":"/am/console"}
```
This is the default redirect url for the top level realm.

See Documentation:
https://backstage.forgerock.com/docs/am/7.2/authentication-guide/redirection-url-precedence.html

The issue is the redirect url is to a different host than AM.

> By default, AM trusts all relative URLs and those absolute URLs that are in the same scheme, FQDN, and port as AM. This increases security against possible phishing attacks through open redirect. 
To configure AM to trust other absolute URLs, add them to the Validation Service. If you do not, on login AM will redirect to the user profile or to the administrator console, and on logout to the default logout page in the UI instead.

**Comment by dbadham-fr** [comment] 2022-11-04 11:32
The solution is to setup the Validation Service: https://backstage.forgerock.com/docs/am/7.2/authentication-guide/redirection-url-precedence.html#configure-validation-service

An alternative solution to investigate: could we make AM run on the same domain as IG?
We have configured the Base URL Service for the alpha domain to be the IG URL, however we have not adjusted the Base URL Service in the Global Service Configuration.

**Comment by dbadham-fr** [comment] 2022-11-04 16:32
Fix merged to branch: [issue/254-work-on-fapi-conformance](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/tree/issue/254-work-on-fapi-conformance)

**Closed by dbadham-fr** 2022-11-04 16:32 UTC
